//FAQS
export const FAQS_FETCH_DATA_START = 'FAQS_FETCH_DATA_START';
export const FAQS_FETCH_DATA_SUCCESS = 'FAQS_FETCH_DATA_SUCCESS';
export const FAQS_FETCH_DATA_FAILURE = 'FAQS_FETCH_DATA_FAILURE';