//FAQS
export const FAQS_FETCH_DATA_START = 'FAQS_FETCH_DATA_START';
export const FAQS_FETCH_DATA_SUCCESS = 'FAQS_FETCH_DATA_SUCCESS';
export const FAQS_FETCH_DATA_FAILURE = 'FAQS_FETCH_DATA_FAILURE';

//ORDERS
export const ORDERS_FETCH_DATA_START = 'ORDERS_FETCH_DATA_START';
export const ORDERS_FETCH_DATA_SUCCESS = 'ORDERS_FETCH_DATA_SUCCESS';
export const ORDERS_FETCH_DATA_FAILURE = 'ORDERS_FETCH_DATA_FAILURE';

//INVOICES
export const INVOICES_FETCH_DATA_START = 'INVOICES_FETCH_DATA_START';
export const INVOICES_FETCH_DATA_SUCCESS = 'INVOICES_FETCH_DATA_SUCCESS';
export const INVOICES_FETCH_DATA_FAILURE = 'INVOICES_FETCH_DATA_FAILURE';