//FAQS
export const FAQS_FETCH_DATA_START = 'FAQS_FETCH_DATA_START';
export const FAQS_FETCH_DATA_SUCCESS = 'FAQS_FETCH_DATA_SUCCESS';
export const FAQS_FETCH_DATA_FAILURE = 'FAQS_FETCH_DATA_FAILURE';

//ORDERS
export const ORDERS_FETCH_DATA_START = 'ORDERS_FETCH_DATA_START';
export const ORDERS_FETCH_DATA_SUCCESS = 'ORDERS_FETCH_DATA_SUCCESS';
export const ORDERS_FETCH_DATA_FAILURE = 'ORDERS_FETCH_DATA_FAILURE';

//INVOICES
export const INVOICES_FETCH_DATA_START = 'INVOICES_FETCH_DATA_START';
export const INVOICES_FETCH_DATA_SUCCESS = 'INVOICES_FETCH_DATA_SUCCESS';
export const INVOICES_FETCH_DATA_FAILURE = 'INVOICES_FETCH_DATA_FAILURE';

//MENU
export const MENU_FETCH_DATA_START = 'MENU_FETCH_DATA_START';
export const MENU_FETCH_DATA_SUCCESS = 'MENU_FETCH_DATA_SUCCESS';
export const MENU_FETCH_DATA_FAILURE = 'MENU_FETCH_DATA_FAILURE';

//CONFIGURATIONS OPTIONS
export const CONFIGURATION_OPTIONS_FETCH_DATA_START = 'CONFIGURATION_OPTIONS_FETCH_DATA_START';
export const CONFIGURATION_OPTIONS_FETCH_DATA_SUCCESS = 'CONFIGURATION_OPTIONS_FETCH_DATA_SUCCESS';
export const CONFIGURATION_OPTIONS_FETCH_DATA_FAILURE = 'CONFIGURATION_OPTIONS_FETCH_DATA_FAILURE';

//EVENTS
export const EVENTS_FETCH_DATA_START = 'EVENTS_FETCH_DATA_START';
export const EVENTS_FETCH_DATA_SUCCESS = 'EVENTS_FETCH_DATA_SUCCESS';
export const EVENTS_FETCH_DATA_FAILURE = 'EVENTS_FETCH_DATA_FAILURE';

//CATEGORY ITEMS
export const CATEGORY_ITEMS_FETCH_DATA_START = 'CATEGORY_ITEMS_FETCH_DATA_START';
export const CATEGORY_ITEMS_FETCH_DATA_SUCCESS = 'CATEGORY_ITEMS_FETCH_DATA_SUCCESS';
export const CATEGORY_ITEMS_FETCH_DATA_FAILURE = 'CATEGORY_ITEMS_FETCH_DATA_FAILURE';